DROP DATABASE IF EXISTS world;
CREATE DATABASE WORLD;

DROP ROLE IF EXISTS ro;
DROP ROLE IF EXISTS rw;

CREATE ROLE ro;
ALTER ROLE ro PASSWORD 'ro';
GRANT CONNECT ON DATABASE world TO ro;

CREATE ROLE rw;
ALTER ROLE rw PASSWORD 'rw';
GRANT CONNECT ON DATABASE world TO rw;

\c world;
CREATE EXTENSION citus;

